version: '3.9'

services:
  webserver:
    image: php:8.3-apache
    container_name: php_webserver
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    environment:
      DB_HOST: mysql
      DB_NAME: mydatabase
      DB_USER: root
      DB_PASS: rootpassword
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  db_data:
